import { ProjectProps } from "../_components/ProjectCard"; // Adjust the import path as necessary

export const techCardsItems = [
  {
    name: "Figma",
    description: "Design Tool",
    imageUrl: "/imgs/logos/figma-logo.svg",
    bgColor: "bg-[#0ACF83]/20",
  },
  {
    name: "TypeScript",
    description: "JavaScript but better",
    imageUrl: "/imgs/logos/typescript.svg",
    bgColor: "bg-[#3178C6]/20",
  },
  {
    name: "React",
    description: "JavaScript Library",
    imageUrl: "/imgs/logos/react.svg",
    bgColor: "bg-[#61DAFB]/20",
  },
  {
    name: "NextJS",
    description: "React framework",
    imageUrl: "/imgs/logos/nextjs.svg",
    bgColor: "bg-dark-200/10 dark:bg-white/10",
  },
  {
    name: "Tailwind",
    description: "CSS framework",
    imageUrl: "/imgs/logos/tailwind.svg",
    bgColor: "bg-[#0EA5E9]/20",
  },
  {
    name: "Git",
    description: "Version control",
    imageUrl: "/imgs/logos/git.svg",
    bgColor: "bg-[#F1502F]/20",
  },
  {
    name: "Supabase",
    description: "Backend tool",
    imageUrl: "/imgs/logos/supabase.svg",
    bgColor: "bg-[#3ECF8E]/20",
  },
  {
    name: "Appwrite",
    description: "Backend tool",
    imageUrl: "/imgs/logos/appwrite.svg",
    bgColor: "bg-[#F02D65]/20",
  },
  {
    name: "Python",
    description: "Programming Language",
    imageUrl: "https://www.vectorlogo.zone/logos/python/python-icon.svg",
    bgColor: "bg-[#3776AB]/20",
    tooltip: "4+ years of experience in Python development. Built numerous data science projects including predictive models, data analysis pipelines, and machine learning applications.",
  },
  {
    name: "Django",
    description: "Web Framework",
    imageUrl: "https://cdn.worldvectorlogo.com/logos/django.svg",
    bgColor: "bg-[#092E20]/20",
    tooltip: "Built web applications for data visualization and ML model deployment. Experience in creating RESTful APIs and database integration.",
  },
  {
    name: "MongoDB",
    description: "NoSQL Database",
    imageUrl: "https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg",
    bgColor: "bg-[#47A248]/20",
    tooltip: "Experience in handling large-scale datasets and implementing data pipelines. Used MongoDB for storing and retrieving unstructured data in ML projects.",
  },
  {
    name: "PostgreSQL",
    description: "SQL Database",
    imageUrl: "https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg",
    bgColor: "bg-[#336791]/20",
    tooltip: "Proficient in complex SQL queries, database design, and data modeling. Used PostgreSQL for structured data storage in various analytics projects.",
  },
  {
    name: "TensorFlow",
    description: "ML Framework",
    imageUrl: "https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg",
    bgColor: "bg-[#FF6F00]/20",
    tooltip: "Built and trained deep learning models for computer vision and NLP tasks. Experience with CNN, RNN architectures and transfer learning.",
  },
  {
    name: "PyTorch",
    description: "ML Framework",
    imageUrl: "https://www.vectorlogo.zone/logos/pytorch/pytorch-icon.svg",
    bgColor: "bg-[#EE4C2C]/20",
    tooltip: "Developed deep learning models for computer vision and reinforcement learning projects. Experience with custom neural network architectures.",
  },
  {
    name: "NumPy",
    description: "Scientific Computing",
    imageUrl: "https://www.vectorlogo.zone/logos/numpy/numpy-icon.svg",
    bgColor: "bg-[#4DABCF]/20",
    tooltip: "Extensive experience with NumPy for numerical computing, matrix operations, and scientific calculations in projects like neural networks and statistical analysis.",
  },
  {
    name: "Pandas",
    description: "Data Analysis",
    imageUrl: "https://raw.githubusercontent.com/devicons/devicon/master/icons/pandas/pandas-original.svg",
    bgColor: "bg-[#150458]/20",
    tooltip: "Strong proficiency in data manipulation and analysis using Pandas. Used in projects for data cleaning, transformation, and exploratory data analysis.",
  },
  {
    name: "Scikit-learn",
    description: "Machine Learning",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg",
    bgColor: "bg-[#F7931E]/20",
    tooltip: "Implemented various ML algorithms using Scikit-learn including classification, regression, and clustering. Used in projects like Bike Rental Prediction and Titanic Survival Analysis.",
  },
  {
    name: "Matplotlib",
    description: "Data Visualization",
    imageUrl: "https://www.vectorlogo.zone/logos/plot_ly/plot_ly-icon.svg",
    bgColor: "bg-[#11557C]/20",
    tooltip: "Created comprehensive data visualizations for analysis and presentations. Proficient in creating custom plots, statistical visualizations, and interactive charts.",
  },
  {
    name: "Seaborn",
    description: "Statistical Visualization",
    imageUrl: "https://raw.githubusercontent.com/mwaskom/seaborn/master/doc/_static/logo-mark-lightbg.svg",
    bgColor: "bg-[#4A72B8]/20",
    tooltip: "Used Seaborn for statistical data visualization in various projects. Expert in creating correlation matrices, distribution plots, and regression visualizations.",
  },
  {
    name: "Power BI",
    description: "Business Intelligence",
    imageUrl: "https://www.vectorlogo.zone/logos/microsoft_powerbi/microsoft_powerbi-icon.svg",
    bgColor: "bg-[#F2C811]/20",
    tooltip: "Created interactive dashboards and reports for business analytics. Experience with DAX, data modeling, and custom visualizations.",
  },
  {
    name: "Tableau",
    description: "Data Visualization",
    imageUrl: "https://cdn.worldvectorlogo.com/logos/tableau-software.svg",
    bgColor: "bg-[#E97627]/20",
    tooltip: "Developed interactive dashboards for sales analysis and performance tracking. Skilled in data storytelling and creating impactful visualizations.",
  },
  {
    name: "R",
    description: "Statistical Computing",
    imageUrl: "https://www.vectorlogo.zone/logos/r-project/r-project-icon.svg",
    bgColor: "bg-[#276DC3]/20",
    tooltip: "Used R for statistical analysis and modeling. Experience with ggplot2, dplyr, and other tidyverse packages for data manipulation and visualization.",
  },
  {
    name: "Jupyter",
    description: "Interactive Computing",
    imageUrl: "https://www.vectorlogo.zone/logos/jupyter/jupyter-icon.svg",
    bgColor: "bg-[#F37626]/20",
    tooltip: "Extensive use of Jupyter notebooks for data analysis, model development, and creating reproducible research documents. Skilled in interactive data exploration.",
  },
  {
    name: "Apache Spark",
    description: "Big Data Processing",
    imageUrl: "https://www.vectorlogo.zone/logos/apache_spark/apache_spark-icon.svg",
    bgColor: "bg-[#E25A1C]/20",
    tooltip: "Experience with big data processing and distributed computing. Used Spark for large-scale data analysis and machine learning pipelines.",
  },
  {
    name: "Excel",
    description: "Data Analysis",
    imageUrl: "https://www.vectorlogo.zone/logos/microsoft_excel/microsoft_excel-icon.svg",
    bgColor: "bg-[#217346]/20",
    tooltip: "Advanced Excel skills including pivot tables, VLOOKUP, macros, and data analysis. Created automated reports and dashboards for business analytics.",
  },
  {
    name: "Stable Baselines3",
    description: "RL Library",
    imageUrl: "https://www.vectorlogo.zone/logos/python/python-icon.svg",
    bgColor: "bg-[#276DC3]/20",
  },
  {
    name: "SAS",
    description: "Statistical Analysis",
    imageUrl: "https://www.vectorlogo.zone/logos/sas/sas-icon.svg",
    bgColor: "bg-[#00629B]/20",
  },
];

export const portfolioProjects: ProjectProps[] = [

  {
    id: "1",
    projectName: "bike-rental",
    heading: "Bike Rental Prediction",
    subheading: "Neural Networks for Daily Ridership",
    description: "Optimizing Bike Availability: Predicting Daily Ridership with Neural Networks.",
    imageUrl: "/imgs/projects/bike.jpg",
    techStack: ["Python", "Neural Networks", "Data Analysis"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-bike-rental-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Bike-rental-prediction",
  },
  {
    id: "2",
    projectName: "titanic",
    heading: "Titanic Survival Prediction",
    subheading: "Data Analysis of Historic Disaster",
    description: "Predicting Survival: Unraveling the Titanic Disaster with Data.",
    imageUrl: "/imgs/projects/titanic.JPG",
    techStack: ["Python", "Logistic Regression", "Data Science"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Titanic-Disaster-survivor-prediction",
  },
  {
    id: "3",
    projectName: "game-analysis",
    heading: "Video Game Analysis",
    subheading: "K-Means Clustering for Game Sales",
    description: "Picking the Best Games: Clustering Video Game Sales Data with K-Means.",
    imageUrl: "/imgs/projects/game.jpg",
    techStack: ["Python", "K-Means Clustering", "Data Analysis"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Kmeans-Picking-best-computer-game-to-try",
  },
  {
    id: "4",
    projectName: "mnist",
    heading: "MNIST Digit Classification",
    subheading: "2-Layer MLP Implementation",
    description: "Classifying Digits with Precision: A 2-Layer MLP on MNIST Using Mini-Batch",
    imageUrl: "/imgs/projects/digit.webp",
    techStack: ["Python", "Neural Networks", "Machine Learning"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/MLP-MNIST-Python",
  },
  {
    id: "5",
    projectName: "sales-analysis",
    heading: "Sales Analysis Dashboard",
    subheading: "Power BI Visualization",
    description: "Visualizing Success: A Power BI Dashboard for Comprehensive Sales Analysis and Performance Tracking",
    imageUrl: "/imgs/projects/sales.jpg",
    techStack: ["Power BI", "SQL", "Data Visualization"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/-SalesAnalysis-Powebi-And-SQL",
  },
  {
    id: "6",
    projectName: "loan-prediction",
    heading: "Loan Acceptance Prediction",
    subheading: "Optimized Logistic Regression",
    description: "Boosting Conversions: Predicting Personal Loan Acceptance with Optimized Logistic Regression.",
    imageUrl: "/imgs/projects/dataset-cover.jpg",
    techStack: ["Python", "Logistic Regression", "Machine Learning"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Loan-prediction-and-optimization",
  },
  {
    id: "7",
    projectName: "super-mario",
    heading: "Self-Playing Super Mario",
    subheading: "Reinforcement Learning Agent",
    description: "Self-Playing Super Mario: Training an Autonomous Agent with Reinforcement Learning",
    imageUrl: "/imgs/projects/mario.webp",
    techStack: ["Python", "Reinforcement Learning", "AI"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Super-Mario-RL",
  },
  {
    id: "8",
    projectName: "flappy-bird",
    heading: "AI Flappy Bird",
    subheading: "NEAT Algorithm Implementation",
    description: "Flappy Bird on Autopilot: Building and Training an AI Agent with NEAT in Pygame.",
    imageUrl: "/imgs/projects/falppybird.jpg",
    techStack: ["Python", "NEAT", "Pygame"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Flappy-Bird-Reinforcement-Learning",
  },
  {
    id: "9",
    projectName: "aircraft-maintenance",
    heading: "Aircraft Engine Health",
    subheading: "Predictive Maintenance System",
    description: "Forecasting Aircraft Engine Health: Implementing Predictive Maintenance for Failure Prediction and Remaining Useful Life Estimation.",
    imageUrl: "/imgs/projects/airplane.jpeg",
    techStack: ["Python", "Machine Learning", "Predictive Analytics"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/-Predictive-Maintenance-of-Aircraft-Engine",
  },
  {
    id: "10",
    projectName: "tweet-classification",
    heading: "Tweet Classification",
    subheading: "Natural Language Processing",
    description: "Tweet Classification using Natural Language Processing and Machine Learning",
    imageUrl: "/imgs/projects/post-a-job-on-twitter-verified-organizations-64b8531a90397-sej.webp",
    techStack: ["Python", "NLP", "Machine Learning"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Tweet_Classification",
  },
  {
    id: "11",
    projectName: "market-basket",
    heading: "Market Basket Analysis",
    subheading: "Instacart Data Analysis",
    description: "Instacart Market Basket Analysis for Understanding Customer Purchase Patterns",
    imageUrl: "/imgs/projects/Punnets+43.jpg",
    techStack: ["Python", "Data Analysis", "Market Research"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/instacart_orders",
  },
  {
    id: "12",
    projectName: "movie-recommendation",
    heading: "Movie Recommendation",
    subheading: "Content-Based System",
    description: "Movie Recommendation System Using Content-Based Filtering",
    imageUrl: "/imgs/projects/netflix.png",
    techStack: ["Python", "Recommendation Systems", "Machine Learning"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Gudguykartik-Movie_recommendation_system-PYTHON",
  },
  {
    id: "13",
    projectName: "customer-segments",
    heading: "Customer Segmentation",
    subheading: "Unsupervised Learning",
    description: "Unsupervised Learning: Creating Customer Segments",
    imageUrl: "/imgs/projects/customersegement.png",
    techStack: ["Python", "Clustering", "Customer Analytics"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/customer_segementation",
  },
  {
    id: "14",
    projectName: "lane-detection",
    heading: "Lane Detection System",
    subheading: "Computer Vision for Self-Driving",
    description: "Advanced Lane Detection System For Self Driving Cars",
    imageUrl: "/imgs/projects/cover-photo-lane-detection.jpg",
    techStack: ["Python", "Computer Vision", "OpenCV"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Advance_Lane_Detection",
  },
  {
    id: "15",
    projectName: "fashion-recommendation",
    heading: "Fashion Recommendation",
    subheading: "AI-Powered Style Suggestions",
    description: "Fashion Recommendation System Using Machine Learning",
    imageUrl: "/imgs/projects/fashion.jpeg",
    techStack: ["Python", "Machine Learning", "Computer Vision"],
    liveDemoUrl: "https://colab.research.google.com/drive/your-titanic-notebook",
    sourceCodeUrl: "https://github.com/Gudguykartik/Fashion_recommendation",
  },
  {
    id: "16",
    projectName: "mathmind-ai",
    heading: "MathMind AI",
    subheading: "Intelligent Mathematics Problem Solver",
    description: "Advanced AI-powered mathematics problem solver using computer vision and natural language processing. Features step-by-step solution explanations, handwritten equation recognition, and interactive learning modules.",
    imageUrl: "/imgs/projects/mathsolver.jpeg",
    techStack: ["Python", "PyTorch", "OpenCV", "React", "FastAPI", "Docker"],
    liveDemoUrl: "https://mathmind-ai.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/mathmind-ai"
  },
  {
    id: "17",
    projectName: "stylesage-ai",
    heading: "StyleSage AI",
    subheading: "AI-Powered Fashion Platform",
    description: "Full-stack fashion e-commerce platform with AI-powered personal styling. Features include virtual try-on, style recommendations based on user preferences, and real-time outfit generation.",
    imageUrl: "/imgs/projects/fashionstylist.jpeg",
    techStack: ["Python", "TensorFlow", "Next.js", "PostgreSQL", "AWS", "Stripe"],
    liveDemoUrl: "https://stylesage-ai.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/stylesage-ai"
  },
  {
    id: "18",
    projectName: "aiducate",
    heading: "Aiducate",
    subheading: "AI-Enhanced Learning Platform",
    description: "Modern educational platform leveraging AI for personalized learning experiences. Built with Django + HTMX for seamless interactions. Features include smart content recommendations and adaptive learning paths.",
    imageUrl: "/imgs/projects/aiducate.jpeg",
    techStack: ["Python", "Django", "PostgreSQL", "Hugging Face", "Redis"],
    liveDemoUrl: "https://aiducate.dev",
    sourceCodeUrl: "https://github.com/kartikrana/aiducate"
  },
  {
    id: "19",
    projectName: "melodymind",
    heading: "MelodyMind",
    subheading: "AI Music Recommendation Platform",
    description: "Spotify-inspired music platform with AI-powered recommendation system. Features collaborative filtering, content-based filtering, and deep learning for music analysis. Includes real-time audio processing.",
    imageUrl: "/imgs/projects/melodymind.jpeg",
    techStack: ["Python", "TensorFlow", "Next.js", "MongoDB", "Redis", "WebAudio API"],
    liveDemoUrl: "https://melodymind.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/melodymind"
  },
  {
    id: "20",
    projectName: "sentimentscope",
    heading: "SentimentScope",
    subheading: "Advanced Text Analysis Platform",
    description: "Comprehensive text analysis tool using advanced NLP techniques. Analyzes customer feedback, social media posts, and reviews to extract insights, emotions, and trends.",
    imageUrl: "/imgs/projects/sentiment.jpeg",
    techStack: ["Python", "BERT", "Flask", "React", "MongoDB", "Docker"],
    liveDemoUrl: "https://sentimentscope.ai",
    sourceCodeUrl: "https://github.com/kartikrana/sentimentscope"
  },
  {
    id: "21",
    projectName: "dataviz-pro",
    heading: "DataViz Pro",
    subheading: "Interactive Data Visualization",
    description: "Dynamic data visualization platform with real-time analytics capabilities. Creates interactive and customizable visualizations for complex datasets. Features automated chart suggestions.",
    imageUrl: "/imgs/projects/dataviz.jpeg",
    techStack: ["Python", "D3.js", "React", "FastAPI", "PostgreSQL", "Redis"],
    liveDemoUrl: "https://dataviz-pro.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/dataviz-pro"
  },
  {
    id: "22",
    projectName: "stocksense-ai",
    heading: "StockSense AI",
    subheading: "Intelligent Stock Analysis",
    description: "AI-powered stock market analysis tool using machine learning for price prediction and trend analysis. Incorporates sentiment analysis of news and social media.",
    imageUrl: "/imgs/projects/stocksense.jpeg",
    techStack: ["Python", "TensorFlow", "FastAPI", "React", "PostgreSQL", "Redis"],
    liveDemoUrl: "https://stocksense-ai.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/stocksense-ai"
  },
  {
    id: "23",
    projectName: "healthtrack-ai",
    heading: "HealthTrack AI",
    subheading: "Personal Health Analytics",
    description: "AI-driven health monitoring and analytics platform. Uses machine learning for personalized health insights and predictions. Features include activity tracking and health risk assessment.",
    imageUrl: "/imgs/projects/healthtrack.jpeg",
    techStack: ["Python", "TensorFlow", "React Native", "FastAPI", "MongoDB", "AWS"],
    liveDemoUrl: "https://healthtrack-ai.vercel.app",
    sourceCodeUrl: "https://github.com/kartikrana/healthtrack-ai"
  }
];

export const tooltipItems = [
  {
    id: 1,
    name: "Bogdan Aleksic",
    designation: "Great job!",
    image: "/imgs/avatars/bogdan.svg",
  },
  {
    id: 2,
    name: "Djordje Djurovic",
    designation: "Incredibly responsible",
    image: "/imgs/avatars/djordje.jpeg",
  },
  {
    id: 3,
    name: "Anthony Sean",
    designation: "Highly recommended!",
    image: "/imgs/avatars/Anthony.jpg",
  },
  {
    id: 4,
    name: "Alex Finn",
    designation: "Enjoyable experience.",
    image: "/imgs/avatars/Alex.jpg",
  },
];

export const testimonialItems = [
  {
    id: 1,
    stars: 5,
    name: "Alex Finn",
    proffesion: "Lead Web Designer at knots.io",
    description:
      "“Working with Andrija was a very smooth experience from start to finish.  He not only brings strong technical skills to front-end development, but his attention to detail and commitment to delivering pixel-perfect  designs made a huge difference in our project. He is enthusiastic in  suggesting improvements. Always ready to answer questions or provide  updates. If you're looking for a reliable developer who brings  creativity and efficiency to the table, Andrija is the right person!”",
    image: "/imgs/avatars/Alex.jpg",
  },
  {
    id: 2,
    stars: 5,
    name: "Djordje Djurovic",
    proffesion: "CEO at DigitalityLab",
    description:
      "“Andrija is an outstanding frontend specialist and presents consistently high level of work. During our work together, he has demonstrated extraordinary skills in simplifying complex ideas into clean, functional, and visually appealing designs. His communication is to the point and time management is perfect, even for the most pressing deadlines. I would highly recommend him to any company looking to bring on a frontend developer with strong technical skills and an keen eye for design.”",
    image: "/imgs/avatars/djordje.jpeg",
  },
  {
    id: 3,
    stars: 5,
    name: "Anthony Sean",
    proffesion: "Chief Technology Officer at DealJet",
    description:
      "“On several occasions, I have had the privilege to work with Andrija, and he has never failed to impress. While he possesses a great level of knowledge in frontend development, what I find most remarkable about him is his obsession with getting every detail right in order to achieve perfection in the end-user experience. He always pays attention to the project requirements, raises up some pertinent issues, and most importantly delivers beyond the call of duty. Andrija is the kind of person who adds value to the team he's in!”",
    image: "/imgs/avatars/Anthony.jpg",
  },
  {
    id: 4,
    stars: 5,
    name: "Bogdan Aleksic",
    proffesion: "Investment Educator and Crypto Expert",
    description:
      "“I got on board Andrija from Upwork to help me develop a website for my course on blockchain, cryptocurrency, and investment techniques. Because of his effort, I was able to generate considerable sales from my course after launching it, and I have received good reviews about the design and functionality of the website. Andrija is someone I would highly recommend!”",
    image: "/imgs/avatars/bogdan.svg",
  },
];
